//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sidoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoriasDelLibro
    {
        public int I_ID_AUTORIA { get; set; }
        public Nullable<int> I_ID_TIPO_AUTORIA { get; set; }
        public int I_ID_LIBRO { get; set; }
    
        public virtual Autoria CAT_AUTORIA { get; set; }
        public virtual TiposDeAutoria CAT_TIPO_AUTORIA { get; set; }
        public virtual Libro T_LIBRO { get; set; }
    }
}
