//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sidoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autoria
    {
        public Autoria()
        {
            this.T_LIBRO_AUTORIA = new HashSet<AutoriasDelLibro>();
        }
    
        public int I_ID_AUTORIA { get; set; }
        public string VC_NOMBRE { get; set; }
        public bool B_AUTOR_INSTITUCIONAL { get; set; }
    
        public virtual ICollection<AutoriasDelLibro> T_LIBRO_AUTORIA { get; set; }
    }
}
