//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sidoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        public Libro()
        {
            this.T_LIBRO_AUTORIA = new HashSet<AutoriasDelLibro>();
        }
    
        public int I_ID_LIBRO { get; set; }
        public Nullable<int> FK_TIPO_FECHA { get; set; }
        public Nullable<int> I_ID_CATEGORIA_TEMATICA_GEOGRAFICA { get; set; }
        public Nullable<int> I_ID_ESTADO { get; set; }
        public Nullable<int> I_ID_NIVEL_BIBLIOGRAFICO { get; set; }
        public Nullable<int> I_ID_NIVEL_REGISTRO { get; set; }
        public Nullable<int> I_ID_PERIOCIDAD { get; set; }
        public Nullable<int> I_ID_TIPO_DOCUMENTO { get; set; }
        public Nullable<int> I_ID_TIPO_LITERATURA { get; set; }
        public Nullable<int> I_ID_INFORMACION_DESCRIPTIVA { get; set; }
        public string VC_NUMERO_ACCESO { get; set; }
        public string VC_NUMERO_CLASIFICACION { get; set; }
        public string VC_PAGINA { get; set; }
        public string VC_NUMERO_VOLUMEN_MONOG { get; set; }
        public string VC_TITULO_COLEC { get; set; }
        public string VC_SUBTITULO_COLEC { get; set; }
        public string VC_NUMERO_TOTAL_VOLUMEN_COLEC { get; set; }
        public string VC_TITULO_MONOG { get; set; }
        public string VC_SUBTITULO_MONG { get; set; }
        public string VC_EDITOR_INSTITUCIONAL { get; set; }
        public string VC_TITULO_PUB_SER { get; set; }
        public string VC_SUBTITULO_PUB_SER { get; set; }
        public string VC_VOLUMEN_PUB_SER { get; set; }
        public string VC_NUMERO_PUB_SER { get; set; }
        public string VC_EXISTENCIAS_PUB_SER { get; set; }
        public Nullable<short> SI_NUMERO_EJEMPLARES { get; set; }
        public Nullable<System.DateTime> DT_FECHA_PUBLICACION { get; set; }
        public string VC_EDICION { get; set; }
        public string VC_SIMBOLO { get; set; }
        public string VC_ISBN { get; set; }
        public string VC_GRADO_ACADEMICO { get; set; }
        public string VC_INSTITUCION_TESIS { get; set; }
        public string VC_NOTAS_PUB_SER { get; set; }
        public string VC_CATEGORIA_TEMATICA_PRIMARIA { get; set; }
        public string VC_PAISES_PRIMARIOS { get; set; }
        public string VC_DIVISION_ADMINISTRATIVA { get; set; }
        public string VC_RESUMEN { get; set; }
        public Nullable<System.DateTime> DT_ALCANCE_TEMPORAL { get; set; }
        public string VC_SIGLAS { get; set; }
        public string VC_DIRECCION_URL { get; set; }
        public Nullable<System.DateTime> DT_FECHA_INGRESO_DOC { get; set; }
        public string VC_DOCUMENTALISTA { get; set; }
        public Nullable<byte> TI_PRESTAMO_DISPONIBLE { get; set; }
        public string VC_TABLA_CONTENIDO { get; set; }
        public string VC_TEXTO_COMPLETO { get; set; }
        public string VC_PORTADA { get; set; }
        public string VC_CODIGO_BARRA { get; set; }
        public Nullable<int> I_ID_CIUDAD_EDITORIAL { get; set; }
    
        public virtual TematicaGeografica CAT_CATEGORIA_TEMATICA_GEOGRAFICA { get; set; }
        public virtual CiudadEditorial CAT_CIUDAD_EDITORIAL { get; set; }
        public virtual Estado CAT_ESTADO { get; set; }
        public virtual InformacionDescriptiva CAT_INFORMACION_DESCRIPTIVA { get; set; }
        public virtual NivelBibliografico CAT_NIVEL_BIBLIOGRAFICO { get; set; }
        public virtual NivelDeRegistro CAT_NIVEL_REGISTRO { get; set; }
        public virtual Periocidad CAT_PERIOCIDAD { get; set; }
        public virtual Documento CAT_TIPO_DOCUMENTO { get; set; }
        public virtual TipoDeFecha CAT_TIPO_FECHA { get; set; }
        public virtual TipoDeLiteratura CAT_TIPO_LITERATURA { get; set; }
        public virtual ICollection<AutoriasDelLibro> T_LIBRO_AUTORIA { get; set; }
    }
}
