//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sidoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfil
    {
        public Perfil()
        {
            this.T_USUARIO = new HashSet<Usuario>();
        }
    
        public int I_ID_PERFIL { get; set; }
        public string VC_NOMBRE { get; set; }
        public string VC_DESCRIPCION { get; set; }
    
        public virtual ICollection<Usuario> T_USUARIO { get; set; }
    }
}
