//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sidoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDeFecha
    {
        public TipoDeFecha()
        {
            this.T_LIBRO = new HashSet<Libro>();
        }
    
        public int I_ID_TIPO_FECHA { get; set; }
        public string VC_DESCRIPCION { get; set; }
        public string VC_NOMBRE { get; set; }
    
        public virtual ICollection<Libro> T_LIBRO { get; set; }
    }
}
