//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sidoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDeIdentificacion
    {
        public TipoDeIdentificacion()
        {
            this.T_USUARIO = new HashSet<Usuario>();
        }
    
        public int I_ID_TIPO_IDENTIFICACION { get; set; }
        public string VC_DESCRIPCION { get; set; }
    
        public virtual ICollection<Usuario> T_USUARIO { get; set; }
    }
}
