//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inamu.Sidoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int I_ID_USUARIO { get; set; }
        public Nullable<int> I_ID_NIVEL_EDUCATIVO { get; set; }
        public Nullable<int> I_ID_SEXO { get; set; }
        public Nullable<int> I_ID_TIPO_IDENTIFICACION { get; set; }
        public Nullable<int> I_ID_PERFIL { get; set; }
        public string VC_IDENTIFICACION { get; set; }
        public string VC_CONTRASENA { get; set; }
        public string VC_NOMBRE { get; set; }
        public string VC_PRIMER_APELLIDO { get; set; }
        public string VC_SEGUNDO_APELLIDO { get; set; }
        public string VC_CORREO_ELECTRONICO { get; set; }
        public string VC_LUGAR_TRABAJO_ESTUDIO { get; set; }
        public Nullable<bool> B_RECIBIR_NOVEDADES { get; set; }
        public Nullable<System.DateTime> FT_FECHA_CREACION { get; set; }
        public string VC_FIRMA_DIGITAL { get; set; }
        public string VC_NOMBRE_USUARIO { get; set; }
    
        public virtual NivelEducativo CAT_NIVEL_EDUCATIVO { get; set; }
        public virtual Genero CAT_SEXO { get; set; }
        public virtual TipoDeIdentificacion CAT_TIPO_IDENTIFICACION { get; set; }
        public virtual Perfil T_PERFIL { get; set; }
    }
}
